### PR TITLE
ZFIN-7838 put curation nav bar horizontally above publication view page.

### PR DESCRIPTION
**Pull request by cmpich**

### CODE REVIEW

**Comment by cmpich** [comment]
Change in FastaReadProcess file belongs to other jira ticket.

**Comment by rtaylorzfin** [comment]
What do you think of something like this:

`
            <nav class="navbar navbar-light text-center no-gutters border-bottom"
                    style="background-color: #efefef;
                            margin: -1.5rem -1.5rem 1rem -1.5rem;
                            padding-top: 1.1em;
                            padding-bottom: 1.2em;"
                    >
                    <a class="col-sm" href="/action/publication/view/${publication.zdbID}">Old View</a>
                    <a class="col-sm" href="/action/curation/${publication.zdbID}">Curate</a>
                    <a class="col-sm" href="/action/publication/${publication.zdbID}/link">Link</a>
                    <a class="col-sm" href="/action/publication/${publication.zdbID}/edit">Edit</a>
                    <a class="col-sm" href="/action/publication/${publication.zdbID}/track">Track</a>
            </nav>
`

Resulting in this:
Screen Shot 2022-02-21 at 3 19 12 PM

**Comment by rtaylorzfin** [comment]
Could maybe use buttons too:

Screen Shot 2022-02-21 at 3 27 57 PM

**Comment by cmpich** [comment]
I do like the clean separation of the links. The buttons feel too heavy and distracting.

**Comment by ybradford** [comment]
I agree with @cmpich the buttons are too much. Separation of links is good, can other curators view the updates? (most don't follow on Github)

**Comment by cmpich** [comment]
The changes will be visible on TRUNK after this PR goes through. I can let you know Yvonne when it is available and then curators can chime in.

**Comment by cmpich** [comment]
Moved the style part into a css class / file.

**Review by rtaylorzfin — APPROVED** [review]
Looks good

**Pull request merged**
