### PR TITLE
ZFIN-7703

### PR DESCRIPTION
**Pull request by rtaylorzfin**
Introduce service class.
Add related genes as direct attributions when an allele is added to a publication.
Add test to DbUnitTests.

### CODE REVIEW

**Comment by rtaylorzfin** [comment]
Are there any cases where a feature is added to a publication, but we don't want to directly attribute related genes?

**Comment by cmpich** [comment]
> Are there any cases where a feature is added to a publication, but we don't want to directly attribute related genes?

Not that I know of. You might ask a curator for this.

**Comment by ybradford** [comment]
@rtaylorzfin I think we will always want to directly attribute related genes when a feature is added to a publication.

**Review by cmpich — COMMENTED** [review]
Looks good.

**Pull request merged**
